/*
 *   This file was automatically generated by version 1.7 of cextract.
 *   Manual editing not recommended.
 *
 *   Created: Tue May 23 15:25:54 1995
 */
#ifndef PROTOS_H
#define PROTOS_H 1

#if 1

#include <math.h>

#else

extern double acos ( double x );
extern double acosh ( double x );
extern double asin ( double x );
extern double asinh ( double x );
extern double atan ( double x );
extern double atan2 ( double y, double x );
extern double atanh ( double x );
extern double cbrt ( double x );
extern double m_ceil ( double x );
extern double chbevl ( double x, void * array, int n );
extern double cos ( double x );
extern double cosh ( double x );
extern double cosm1 ( double x );
extern double cot ( double x );
extern int drand ( double *a );
extern double exp ( double x );
extern double exp10 ( double x );
extern double expm1 ( double x );
extern double fabs ( double x );
extern double m_floor ( double x );
extern double m_frexp ( double x, int *pw2 );
extern int m_isfinite ( double x );
extern int m_isnan ( double x );
extern double m_ldexp ( double x, int pw2 );
extern double log ( double x );
extern double log10 ( double x );
extern double log1p ( double x );
extern int mtherr ( char *name, int code );
extern double p1evl ( double x, void * coef, int N );
extern double polevl ( double x, void * coef, int N );
extern double pow ( double x, double y );
extern double powi ( double x, int nn );
extern double round ( double x );
extern int signbit ( double x );
extern double sin ( double x );
#if 0
extern int sincos ( double x, double *s, double *c, int flg );
#else
extern int sincos ( double x, double *s, double *c);
#endif

extern double sinh ( double x );
extern double sqrt ( double x );
extern double tan ( double x );
extern double tanh ( double x );
extern double cabs ( cmplx *z );
extern double hypot ( double x, double y );
extern void cneg ( cmplx *z );
extern void cmov ( void *z, void *w );
extern void cadd ( cmplx *a, cmplx *b, cmplx *c );
extern void csub ( cmplx *a, cmplx *b, cmplx *c );
extern void cmul ( cmplx *a, cmplx *b, cmplx *c );
extern void cdiv ( cmplx *a, cmplx *b, cmplx *c );
extern void csqrt ( cmplx *z, cmplx *w );
extern void clog ( cmplx *z, cmplx *w );
extern void cexp ( cmplx *z, cmplx *w );
extern void csin ( cmplx *z, cmplx *w );
extern void ccos ( cmplx *z, cmplx *w );
extern void ctan ( cmplx *z, cmplx *w );
extern void ccot ( cmplx *z, cmplx *w );
extern void casin ( cmplx *z, cmplx *w );
extern void cacos ( cmplx *z, cmplx *w );
extern void catan ( cmplx *z, cmplx *w );

#endif
extern double mth_acos ( double x );
extern double mth_acosh ( double x );
extern double mth_asin ( double x );
extern double mth_asinh ( double x );
extern double mth_atan ( double x );
extern double mth_atan2 ( double y, double x );
extern double mth_atanh ( double x );
extern double mth_cbrt ( double x );
extern double mth_ceil ( double x );
extern double mth_chbevl ( double x, void * array, int n );
extern double mth_cos ( double x );
extern double mth_cosh ( double x );
extern double mth_cosm1 ( double x );
extern double mth_cot ( double x );
extern int mth_drand ( double *a );
extern double mth_exp ( double x );
extern double mth_exp10 ( double x );
extern double mth_expm1 ( double x );
extern double mth_fabs ( double x );
extern double mth_floor ( double x );
extern double mth_frexp ( double x, int *pw2 );
extern int mth_isfinite ( double x );
extern int mth_isnan ( double x );
extern double mth_ldexp ( double x, int pw2 );
extern double mth_log ( double x );
extern double mth_log10 ( double x );
extern double mth_log1p ( double x );
extern int mtherr ( char *name, int code );
extern double mth_p1evl ( double x, void * coef, int N );
extern double mth_polevl ( double x, void * coef, int N );
extern double mth_pow ( double x, double y );
extern double mth_powi ( double x, int nn );
extern double mth_round ( double x );
extern int mth_signbit ( double x );
extern double mth_sin ( double x );
extern int mth_sincos ( double x, double *s, double *c, int flg );
extern double mth_sinh ( double x );
extern double mth_sqrt ( double x );
extern double mth_tan ( double x );
extern double mth_tanh ( double x );
extern double mth_hyperg( double a, double b, double x);

#if 1
/* incomplete type needed by silly prototypes */
typedef struct {} cmplx;
#endif
extern double mth_cabs ( cmplx *z );
extern double mth_hypot ( double x, double y );
extern void mth_cneg ( cmplx *z );
extern void mth_cmov ( void *z, void *w );
extern void mth_cadd ( cmplx *a, cmplx *b, cmplx *c );
extern void mth_csub ( cmplx *a, cmplx *b, cmplx *c );
extern void mth_cmul ( cmplx *a, cmplx *b, cmplx *c );
extern void mth_cdiv ( cmplx *a, cmplx *b, cmplx *c );
extern void mth_csqrt ( cmplx *z, cmplx *w );
extern void mth_clog ( cmplx *z, cmplx *w );
extern void mth_cexp ( cmplx *z, cmplx *w );
extern void mth_csin ( cmplx *z, cmplx *w );
extern void mth_ccos ( cmplx *z, cmplx *w );
extern void mth_ctan ( cmplx *z, cmplx *w );
extern void mth_ccot ( cmplx *z, cmplx *w );
extern void mth_casin ( cmplx *z, cmplx *w );
extern void mth_cacos ( cmplx *z, cmplx *w );
extern void mth_catan ( cmplx *z, cmplx *w );

extern double mth_gamma ( double x );
extern double mth_lgamma ( double x );
extern double nrc_lgamma ( double x );
extern int mth_sgngam;

#include "mth_wrap.h"

#endif /* PROTOS_H */
