#' Ward rotavirus human-challenge dose-response data
#'
#' Grouped binomial infection counts from the Ward et al. rotavirus
#' human-challenge study, in which healthy adult volunteers ingested measured
#' doses of live CJN-strain rotavirus and were monitored for infection. Each row
#' is one dose group, in the raw 3-column shape accepted by [as_dose_response()]:
#' the administered `dose` and the numbers of subjects who did (`positive`) and
#' did not (`negative`) respond. Pass it straight to [as_dose_response()],
#' [analyze_dose_response()], or [read_dose_response()] (via the bundled file, see
#' source) as the canonical example dataset for the package.
#'
#' @format A [tibble][tibble::tibble] with 8 rows and 3 columns:
#' \describe{
#'   \item{dose}{Administered rotavirus dose in focus-forming units (FFU),
#'     spanning roughly seven orders of magnitude (0.009 to 90000).}
#'   \item{positive}{Number of subjects in the dose group who became infected.}
#'   \item{negative}{Number of subjects in the dose group who did not.}
#' }
#' @source Ward RL, Bernstein DI, Young EC, Sherwood JR, Knowlton DR, Schiff GM
#'   (1986). "Human rotavirus studies in volunteers: determination of infectious
#'   dose and serological response to infection." *Journal of Infectious
#'   Diseases*, 154(5), 871-880. Distributed with the package at
#'   `inst/extdata/Ward_rotavirus.txt`; regenerated by `data-raw/ward_rotavirus.R`.
"ward_rotavirus"
